### ISSUE TITLE
The repository lacks a license.

### ISSUE THREAD

**Issue by enitihas** [alexeygrigorev/mastering-java-data-science#1]
Hi!
I stumbled across this repo after reading the book. It is nice to have all the code examples in the book available online, but the repo doesn't specify a license to the code. The [Publisher's repo](https://github.com/PacktPublishing/Mastering-Java-for-Data-Science) does have a license file, specifying the MIT license. Please consider adding a license file if you want to allow people to use the code.

**Comment by alexeygrigorev** [comment]
If you can create a pull request, I'll be happy to merge it. Thank you!
